# Generated by Django 3.2.15 on 2022-09-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_generallog_componentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='Is Enable'),
        ),
    ]
